### ISSUE TITLE
Pokeget by default has shiny big, shiny small, and shiny forms.

### ISSUE THREAD

**Issue by talwat** [acxz/pokeshell#1]
Heya acxz! I made some updates to add shiny small sprites by default, and pokeget has always had shiny big & small forms. It would be really cool if you could update the table :)

Thanks!

**Comment by acxz** [comment]
For shiny big, the reason why I put an X is because they are not used by default, I can update the table to add a note that they are available, but not on by default. I don't consider the pokemon reborn art as shinies but rather as just fanart.

> add shiny small sprites by default

Nice! Can you update your readme/usage to reflect that? https://github.com/talwat/pokeget/blob/main/USAGE.md#-shiny

I'll go ahead and change it to a check

> small forms

I can't seem to get this to work, can you give me an example use case. Trying `pokeget -small castform-sunny` or `pokeget -small castform_sunny` does not work.

**Comment by talwat** [comment]
Sure. I also updated my USAGE.md, thanks!
