### ISSUE TITLE
Stop printing pokemon names and download full dataset

### ISSUE THREAD

**Issue by quentinmarolleau** [acxz/pokeshell#10]
Hello, thanks for this very cool project.

I have the following config:
![image](https://user-images.githubusercontent.com/30953121/201191723-be430f06-641a-4e8a-a725-80b60e2ded61.png)

I want to add `pokeshell random,1, random,2, random,3, random random random` to my `fish_greeting.fish` function
to display a random team of 6 pokemons when opening a new terminal emulator window.

![image](https://user-images.githubusercontent.com/30953121/201191989-e7043810-83a2-4a3f-ab01-9d4ab606e341.png)

First, it would be nice to have the possibility not to display the disgracious list of pokemon names, on the top of the window.

Then, is there a way to force the downloading of the full dataset of sprites in the `.cache` directory, in order to always have a faster printing?

**Comment by acxz** [comment]
These are some good ideas!

It should be simple enough to add a flag to disable the printing of the name.
For downloading the full dataset I can add some scripts that when run will download all the files associated with that option. For example `./download-small-sprites.sh`, `./download-big-sprites.sh`, `./download-animated-sprites.sh`.

Since holiday season is coming up, I don't know when I'll get around to adding this tho. But I'll def add it to the roadmap.

**Comment by quentinmarolleau** [comment]
Thanks, that is exactly the type of ideas I was thinking about.

Unfortunately I am not used to shell script developpement, and I do not think that I could help with this...

**Comment by acxz** [comment]
Showing the names is now behind a flag (`-n`, `--show-name`). You shouldn't see any more names unless you want to. https://github.com/acxz/pokeshell/commit/94963dd7b869851eab95c4f0b15964ce335cc935

I'll close this issue now, for the offline dataset, see: https://github.com/acxz/pokeshell/issues/9

![image](https://github.com/user-attachments/assets/0c5fba7f-0642-4ac2-82dc-89e3d16ed78d)

![image](https://github.com/user-attachments/assets/e2b31145-9221-4a06-a15e-b25a36d6a09e)
