### ISSUE TITLE
Pokeshell not outputing to neowofetch

### ISSUE THREAD

**Issue by cinnamonbunbuns** [acxz/pokeshell#19]
I have attached my .conf file for Neofetch and am unaware what is causing the issue. I added the lines in the guide to this conf file (Renamed to .txt so I could upload it) so it should be outputting Celebi, but all it does it output the mint logo

![image](https://github.com/user-attachments/assets/c5dc631e-fe43-489a-8039-6fd7c458cb06)
[config.txt](https://github.com/user-attachments/files/16705497/config.txt)

If I type pokeshell celebi it displays an image of Celebi as intended.

I am using zsh with oh-my-zsh but I don't think this would matter given the command works as intended

If this is something silly please forgive me I am new to using this.

**Comment by acxz** [comment]
I'm so sorry @cinnamonbunbuns (i love your name btw!) for the late response.

It looks like I messed up the example with the neowofetch integration in the readme.

I made a commit to fix the readme:
https://github.com/acxz/pokeshell/commit/1adbc4097efadbad838e7744e9fe6fbe1579f334

basically you have `image_source=${pokeshell celebi)`, but it should be `image_source=$(pokeshell celebi)` notice that you should use parentheses instead of the curly brace you have.

I'm gonna go ahead and close this, but if you still have trouble feel free to comment.
