### ISSUE TITLE
Sprites looking distorted on Pop_OS! 22.04

### ISSUE THREAD

**Issue by Ysujy** [acxz/pokeshell#6]
**OS:** 
Pop_OS! 22.04

**Dependencies:** 
bash/jammy,now 5.1-6ubuntu1 amd64
curl/jammy-security,jammy-updates,now 7.81.0-1ubuntu1.3 amd64
jq/jammy,now 1.6-2.1ubuntu3 amd64
imagemagick/jammy,now 8:6.9.11.60+dfsg-1.3build2 amd64
chafa/jammy,now 1.8.0-1 amd64

**Fonts used**
[Powerline](https://github.com/powerline/fonts)
Noto Mono

**Terminals used**
Gnome Terminal 
Alacritty

**Shell**
zsh
bash

Output of `$ pokeshell random`

![image](https://user-images.githubusercontent.com/50801235/185699128-8f45c75d-9ee4-4809-a312-5bd875d18526.png)

Output of `$ pokeshell random -a`

![pokeshell](https://user-images.githubusercontent.com/50801235/185704066-f00dc6c6-9f2f-4a95-8b57-f04514a7fec7.gif)

The distortion might be harder to make out with animated sprites, but they're still present.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Thank you for creating such a cool project. I hope we can get to the bottom of this issue.

**Comment by acxz** [comment]
Thanks for making an issue!

So I actually think they don't look distorted. Can you clarify what kind of output you would like? Are you looking for true image support like sixels/iTerm2/kitty protocols?

**Comment by Ysujy** [comment]
You're right!!! I didn't know that neither Gnome Terminal nor Alacritty have true image support. Just tried Kitty and the output is looking way better. 

Unfortunately, animated sprites are still looking kinda distorted 

![Screenshot from 2022-08-20 00-40-25](https://user-images.githubusercontent.com/50801235/185716175-14a01c86-8977-4792-88ad-37ca99c9f0be.png)

As compared to the image in the README

![Screenshot from 2022-08-20 00-43-29](https://user-images.githubusercontent.com/50801235/185716274-8845f840-28fd-4419-bf7f-63858c3dc13d.png)

**Comment by acxz** [comment]
Nice glad to hear you got it working!

For the animations that you see on the readme, an older version of pokeshell was used that utilized `timg`. I recently made the switch over to `chafa` since it overall has more support. However, one open issue it has is that it doesn't play nice with gifs for the kitty terminal.

See the following issue: https://github.com/hpjansson/chafa/issues/104

We can do two things, wait for chafa to fix their kitty support, or add timg support back in. The time it takes to add timg support, chafa will probably have the issue resolved, so we should probably just wait on it.

**Comment by Ysujy** [comment]
Glad to hear that there might be a fix under way. Anyway, thank you for helping out and have a good one.
